language: c
matrix:
  include:
  - env: GHCVER=7.10.3 RESOLVER=lts-6.12 PY=3.4
    addons:
      apt:
        sources: [hvr-ghc, deadsnakes]
        packages: [ghc-7.10.3, python3.4, libgmp]
  - env: GHCVER=7.10.3 RESOLVER=lts-6.12 PY=3.5
    addons:
      apt:
        sources: [hvr-ghc, deadsnakes]
        packages: [ghc-7.10.3, python3.5, libgmp]
  - env: GHCVER=8.0.1 RESOLVER=nightly-2016-08-15 PY=3.4
    addons:
      apt:
        sources: [hvr-ghc, deadsnakes]
        packages: [ghc-8.0.1, python3.4, libgmp]
  - env: GHCVER=8.0.1 RESOLVER=nightly-2016-08-15 PY=3.5
    addons:
      apt:
        sources: [hvr-ghc, deadsnakes]
        packages: [ghc-8.0.1, python3.5, libgmp]
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/.pyvenv"
before_install:
- mkdir -p "$HOME/.local/bin"
- export PATH="$HOME/.local/bin:$PATH"
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C "$HOME/.local/bin" '*/stack'
- curl -o "$HOME/.local/bin/travis_long" -L https://raw.githubusercontent.com/futurice/fum2github/master/travis_long
- chmod +x "$HOME/.local/bin/travis_long"
install:
- 'sed -E "s/resolver\s*:\s*.*/resolver: $RESOLVER/" stack.yaml > stack-new.yml'
- mv stack-new.yml stack.yml
- travis_long stack --no-terminal setup
- pip install --user virtualenv
- if [[ ! -f "$HOME/.pyvenv/bin/activate" ]]; then virtualenv -p "$(which python$PY)" "$HOME/.pyvenv"; fi
- '"$HOME/.pyvenv/bin/pip" install --upgrade pip setuptools'
- '"$HOME/.pyvenv/bin/pip" install git+git://github.com/spoqa/nirum-python.git'
- if [[ "$PY" = "3.4" ]]; then "$HOME/.pyvenv/bin/pip" install --upgrade typing; fi  # FIXME
script:
- source "$HOME/.pyvenv/bin/activate" && stack --no-terminal test
