resolver: lts-12.0
flags: {}
packages:
- '.'
extra-deps:
- uri-0.1.6.4
  # No in the Stackage LTS 10.7
## INSERT CODECOV HERE -- DO NOT REMOVE THIS COMMENT. SEE ALSO ISSUE #156. ##
extra-package-dbs: []
ghc-options:
  "$locals": -fhide-source-paths
# http://hsyl20.fr/home/posts/2018-01-15-ghc-hiding-source-and-object-paths.html

require-stack-version:
  # CHECK: If we change the minimum version of Stack the download URLs in
  # *appveyor.yml* file also should be updated.
  ">=1.6.5"
